In [1]:
!pip3 install torch

In [0]:
import torch

In [0]:
t_one = torch.tensor([1,2,3])
t_two = torch.tensor([3,4,5])

In [5]:
t_one + t_two

tensor([4, 6, 8])

In [0]:
t3 = torch.tensor([1,2,3,4,5,6]).view(2,3)
t4 = torch.tensor([4,5,6,7,8,9]).view(3,2)

In [7]:
torch.matmul(t3,t4)

tensor([[ 40,  46],
        [ 94, 109]])

In [9]:
e = torch.empty(2,2)
e

tensor([[1.7614e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

In [10]:
torch.rand(2,2)

tensor([[0.8373, 0.2184],
        [0.9839, 0.1764]])

In [11]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.full((2,2),3)

tensor([[3., 3.],
        [3., 3.]])

In [13]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [15]:
import numpy as np
n = np.linspace(0,5,5)
n

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
torch.tensor(n)

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64)

In [21]:
torch.ones(3,3,dtype = torch.float)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
eye = torch.eye(3,3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
eye - torch.ones(3,3)

tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [25]:
eye * 3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [26]:
eye / 3

tensor([[0.3333, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.3333]])

In [27]:
eye * torch.full((3,3),4)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [28]:
x = torch.rand(3,4)
y = torch.rand(4,3)
x@y

tensor([[1.2476, 1.0334, 1.2470],
        [2.0854, 1.4472, 2.0683],
        [1.2348, 1.3043, 1.3799]])